### ISSUE TITLE
对Android 15提供支持

### ISSUE THREAD

**Issue by Bei-Chen-Leo** [WindySha/Xpatch#132]
近期，我更新了OriginOS 5也就是安卓15，打开任何一个被破解的软件均闪退，尝试重新用工具破解再打开仍然闪退

**Comment by feiyihao** [comment]
我也是安卓15，不能打补丁，全部闪退

**Comment by Mubai-meng** [comment]
作者好像放弃了，一年多没更新了

**Comment by WindySha** [comment]
Please try v6.0,  xpatch-v6.0.jar : https://github.com/WindySha/Xpatch/releases/tag/v6.0
Fix hook crash on android 14 and 15.
If it is still crashed on android 15, then  try to repackage the apk use '--dex' mode. 
And let me know if it works or not, thank you.
