### ISSUE TITLE
楼主考虑过文件校验吗

### ISSUE THREAD

**Issue by fanmingyi** [WindySha/Xpatch#17]
文件校验问题楼主考虑过吗？二次打码会导致dex变化 。放入jni层进行文件校验

**Comment by WindySha** [comment]
暂时未考虑此问题，具体是碰到什么问题吗

**Comment by yuyachen** [comment]
app会校验apk 文件的 md5

**Comment by WindySha** [comment]
4.2.0的app已经增加绕过文件校验的功能
https://github.com/WindySha/xposed-tool-app
