### ISSUE TITLE
解析软件包时出现问题

### ISSUE THREAD

**Issue by lwmacct** [WindySha/Xpatch#24]
腾讯视频  
版本：7.0.8.19572
--
大小：39.3MB
更新：2019-05-15
系统：Android 4.0或更高版本
http://gdown.baidu.com/data/wisegame/7f49faeba8a42348/tengxunshipin_19572.apk
Xpatch 1.4

M:\myFile\Android\Xpatch>java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

M:\myFile\Android\Xpatch>java -jar xpatch-1.4.jar
Please choose one apk file you want to process.
options:
 -c,--crach                   disable craching the apk's signature.
 -f,--force                   force overwrite
 -h,--help                    Print this help message
 -k,--keep                    not delete the jar file that is changed by dex2jar
                               and the apk zip files
 -l,--log                     show all the debug logs
 -o,--output <out-apk-file>   output .apk file, default is $source_apk_dir/[file
                              -name]-xposed-signed.apk
 -xm,--xposed-modules <arg>   the xposed mpdule files to be packaged into the ap
                              k, multi files should be seperated by :(mac) or ;(
                              win)
version: 1.4

M:\myFile\Android\Xpatch>java -jar xpatch-1.4.jar help
 The source apk file not exsit, please choose another one.  current apk file is = help

M:\myFile\Android\Xpatch>java -jar xpatch-1.4.jar help -help
ERROR: Unrecognized option: -help
options:
 -c,--crach                   disable craching the apk's signature.
 -f,--force                   force overwrite
 -h,--help                    Print this help message
 -k,--keep                    not delete the jar file that is changed by dex2jar
                               and the apk zip files
 -l,--log                     show all the debug logs
 -o,--output <out-apk-file>   output .apk file, default is $source_apk_dir/[file
                              -name]-xposed-signed.apk
 -xm,--xposed-modules <arg>   the xposed mpdule files to be packaged into the ap
                              k, multi files should be seperated by :(mac) or ;(
                              win)
version: 1.4

M:\myFile\Android\Xpatch>java -jar xpatch-1.4.jar qqsp.apk
 !!!!! output apk path -->  qqsp-xposed-signed.apk  disableCrackSignature --> false
  getApkSignInfo  result -->  [
[
  Version: V3
  Subject: CN=kody, OU=multimedia, O=tx, L=shenzhen, ST=shenzhen, C=86
  Signature Algorithm: SHA1withRSA, OID = 1.2.840.113549.1.1.5

  Key:  Sun RSA public key, 1024 bits
  modulus: 125486394975549297646594873750652312541655516739042102003450892939723969590097020267415069057522633474603141814210243547311004818808575624800088861034897074854258436636941361520947916836794819311704976323228801514281495389338117338820306454498329326105245660814972723589164203363179310625693441661864845358009
  public exponent: 65537
  Validity: [From: Mon Aug 23 17:10:55 CST 2010,
               To: Sun Dec 24 17:10:55 CST 3009]
  Issuer: CN=kody, OU=multimedia, O=tx, L=shenzhen, ST=shenzhen, C=86
  SerialNumber: [    4c723b1f]

]
  Algorithm: [SHA1withRSA]
  Signature:
0000: 22 6A F3 BB 96 B4 D0 89   34 C3 BA 91 AA 51 B3 60  "j......4....Q.`
0010: A8 C8 4D F4 55 C8 07 3D   2D BF C7 8D EA FF DF 56  ..M.U..=-......V
0020: 98 B7 76 6C 6A 8E 94 78   5F 84 F5 EC 7B 5B 3C 13  ..vlj..x_....[<.
0030: 97 77 96 C7 2C A9 18 6B   15 57 D2 44 36 2B 36 6E  .w..,..k.W.D6+6n
0040: 45 5E 01 47 94 40 C0 93   B7 61 FA 85 3E 00 EE 62  E^.G.@...a..>..b
0050: 04 53 55 EA DB 2A E9 03   67 7B D3 2B CC BD 89 E7  .SU..*..g..+....
0060: 4C 95 CA 83 8F FC 01 CE   D1 3D B6 F1 53 88 E5 56  L........=..S..V
0070: A8 A8 FE EF 41 90 DF 1E   EF 10 D9 B9 94 5B 42 12  ....A........[B.

]
dex2jar M:\myFile\Android\Xpatch\2019-05-27-11-35-43-tmp\qqsp-apk-unzip-files\classes.dex -> M:\myFile\Android\Xpatch\2019-05-27-11-35-43-tmp\output-jar.jar  baseName =classes
jar2dex M:\myFile\Android\Xpatch\2019-05-27-11-35-43-tmp\output-jar.jar -> M:\myFile\Android\Xpatch\2019-05-27-11-35-43-tmp\qqsp-apk-unzip-files\classes.dex
call com.android.dx.command.Main.main[--dex, --no-strict, --output=M:\myFile\Android\Xpatch\2019-05-27-11-35-43-tmp\qqsp-apk-unzip-files\classes.dex, M:\myFile\Android\Xpatch\2019-05-27-11-35-43-tmp\output-jar.jar]
use default jarsigner to sign apk failed，and try again, fail msg is :java.io.IOException: Cannot run program "jarsigner": CreateProcess error=2, 系统找不到指定的文件。
use inner jarsigner to sign apk failed, sign it yourself fail msg is :java.io.IOException: Cannot run program "chmod": CreateProcess error=2, 系统找不到指定的文件。

M:\myFile\Android\Xpatch>

**Comment by WindySha** [comment]
3.0版本修复此问题
