### ISSUE TITLE
使用Xpatch打包完微信并安装后，微信授权登录提示“未安装微信”

### ISSUE THREAD

**Issue by siyujie** [WindySha/Xpatch#28]
使用Xpatch打包完微信并安装后，微信授权登录提示“未安装微信”

**Comment by siyujie** [comment]
感觉和太极有些相似

**Comment by WindySha** [comment]
微信登录SDK中做了签名校验导致的，需要破解需要登录的app，hook获取微信app的签名接口

**Comment by siyujie** [comment]
如果是签名校验导致的不应该提示类似签名不正确的文字吗？这个提示的未安装微信，不太像签名的问题
