### ISSUE TITLE
疑惑

### ISSUE THREAD

**Issue by fire-keeper** [WindySha/Xpatch#32]
我对你的项目十分感兴趣,但是对于如何使用Xpatch有许多疑惑.
我的理解是, 通过Xpatch修改app使其能加载Xposed模块, 安装修改后的apk文件并安装想要使用的xposed模块(不安装xposed框架,不激活?). 
我的理解有什么不对的地方吗?

**Comment by WindySha** [comment]
你的理解很正确。

**Comment by WindySha** [comment]
不需要安装xposed框架, 默认激活所有已经安装的xposed模块，需要激活指定的模块，请按照readme文档来操作。
