### ISSUE TITLE
打包失败

### ISSUE THREAD

**Issue by ZxyTx** [WindySha/Xpatch#37]
use default jarsigner to sign apk failed，and try again, fail msg is :java.io.IO
Exception: Cannot run program "jarsigner": CreateProcess error=2, 系统找不到指定
的文件。
use inner jarsigner to sign apk failed, sign it yourself fail msg is :java.io.IO
Exception: Cannot run program "chmod": CreateProcess error=2, 系统找不到指定的文
件。

这个怎么回事，我使用的xpatch-2.0.jar

**Comment by WindySha** [comment]
在哪里运行的？window,mac,android？

**Comment by ZxyTx** [comment]
> 在哪里运行的？window,mac,android？

window

**Comment by ZxyTx** [comment]
@WindySha 我尝试着在输出的apk中添加了jar包中的so文件，运行成功
