### ISSUE TITLE
Xposed模块的xposed_init文件里有多个个hook子类时，只有第一个生效

### ISSUE THREAD

**Issue by sunzqAndroid** [WindySha/Xpatch#40]
Xposed模块的xposed_init文件里有多个个hook子类时，只有第一个生效

如：
xposed_init文件内容如下
com.xposed.demo.HookReturnValue
com.xposed.demo.HookMethodParms

只有HookReturnValue类的hook生效了。而用xposed_installer安装，2个子类都会生效

**Comment by WindySha** [comment]
3.0版本修复此问题
