### ISSUE TITLE
博主解决了dex2jar 运行在 Android设备上了吗

### ISSUE THREAD

**Issue by Cuieney** [WindySha/Xpatch#43]
Android 运行dex2jar实现设备端进行修改dex

**Comment by WindySha** [comment]
未解决，Android上不使用dex2jar修改dex文件，也可以实现Xpatch一样的功能，app下载地址：
https://xposed-tool-app.oss-cn-beijing.aliyuncs.com/data/xposed_tool_v1.0.2.apk

**Comment by Cuieney** [comment]
想了解博主是怎么解决这个问题的啊，可以在公众号出一篇文章吗
