### ISSUE TITLE
打包钉钉的时候安装过7-8小时无法联网

### ISSUE THREAD

**Issue by Cross2pro** [WindySha/Xpatch#51]
这个在模拟器上经过测试（模拟器不支持Xpatch，所以测试的是我写的模块）是正常的。

**而在真机上过了7-8个小时出现连接服务器失败的问题。**
**而且退出后台（系统自动清理或者手动清理）重新进入都会马上出现这个问题**，不知道是模块加载时候的问题吗，由于真机没有root，看不到相关的日志，因此提个issue

**Comment by qq1091192337** [comment]
作者能不能弄个稳定性更好点的hook框架，FastHook看看怎么样？
