### ISSUE TITLE
最新版支付宝10.1.92.7000打包后无法使用

### ISSUE THREAD

**Issue by ckbkdj** [WindySha/Xpatch#52]
1.提示系统出错,正在排查
2.支付宝版本号10.1.92.7000
3.仅使用最普通的破解方式(选择破解签名)其他没有任何选择

**Comment by WindySha** [comment]
应该是支付宝做了加固处理，防止二次打包，因此需要自定逆向支付宝，使用xposed插件绕过相关加固措施
