### ISSUE TITLE
Xpatch应用程序的源代码 - Source code for Xpatch App

### ISSUE THREAD

**Issue by akhilkedia** [WindySha/Xpatch#55]
Thank you so much for this open-source project, it works exactly as described.
Can you consider open-sourcing the code for Xpatch apk?

非常感谢您这个开源项目，它完全按照描述的方式工作。
您可以考虑将Xpatch apk的代码开源吗？

**Comment by WindySha** [comment]
It is not perfect enought, and many more works are going to be done.before I open source it.

**Comment by WindySha** [comment]
It is not perfect enought, and many more works are going to be done.
Before it is open-sourced, I'll make it better. This work needs one or two month.

**Comment by WindySha** [comment]
It is not perfect enought, and many more works are going to be done.
Before it is open-sourced, I'll make it better. This work needs one or two month.
Maybe it will be open-sourced in August.
