### ISSUE TITLE
把模块打包进apk后，模块如何访问自己的resource？

### ISSUE THREAD

**Issue by yujincheng08** [WindySha/Xpatch#57]
之前我都是用`createPackageContext(BuildConfig.APPLICATION_ID, Context.CONTEXT_IGNORE_SECURITY)`来获取模块本身资源的。如果把模块打包进apk之后，模块本身是没有安装的，这样就不能用`createPackageContext`了。而`ResourceHook`也不能用，那如何访问自己的resource呢？（我现在是想把模块preference的xml加载起来然后再app里面搞一个设置页面）

**Comment by WindySha** [comment]
可以参考[FridaXposedModule](https://github.com/WindySha/FridaXposedModule)项目里的 [AppUtils](https://github.com/WindySha/FridaXposedModule/blob/master/app/src/main/java/com/wind/frida/xposed/utils/AppUtils.java)里的getPluginApkPath()方法，获取到当前模块文件的路径，然后反射构造一个AssetManager，反射调用其addAssetPath方法，将此路径设进去，即可以得到模块的AssetManager。

**Comment by yujincheng08** [comment]
@WindySha 测试了一下，获取出来的path跟`IXposedHookZygoteInit.StartupParam.modulePath`是一样的，是个`.so`文件的路径对吗？
