### ISSUE TITLE
可否给Xpatch app增加Maniest文件方式和老版本中的修改dex文件的方式开关

### ISSUE THREAD

**Issue by aylz10** [WindySha/Xpatch#66]
jar3.0默认使用修改Maniest文件方式，植入初始化代码，同时，支持更改为老版本中的修改dex文件的方式植入代码
但是Xpatch app只能默认Maniest方式，可否新版本增加一个切换选项方便二次修改过加固校验的应用
大部分过加固校验的方式都是Maniest方式，会冲突

**Comment by WindySha** [comment]
暂时无法再app端增加修改dex的方式，因为这个过程需要使用到dex2jar这个库，但这个库无法在Android系统上运行
