### ISSUE TITLE
第三方应用调用问题

### ISSUE THREAD

**Issue by flyingshare** [WindySha/Xpatch#69]
重签名后的应用无法被第三方调用者识别，例如微信登陆，三方应用会提示未安装微信，这种问题有啥解决思路没有

**Comment by WindySha** [comment]
这种问题，要对第三方应用重新打包，使用xposed模块修改其获取微信签名的接口，使其返回官方微信签名的signture string。或者在root环境，使用xposed模块来修改第三方应用。
