### ISSUE TITLE
多个dex文件时异常

### ISSUE THREAD

**Issue by YekaterinaCui** [WindySha/Xpatch#7]
trouble writing output: Too many method references to fit in one dex file: 65537; max is 65536.
You may try using multi-dex. If multi-dex is enabled then the list of classes for the main dex list is too large.
References by package:

**Comment by WindySha** [comment]
如何复现问题

**Comment by YekaterinaCui** [comment]
> 如何复现问题

这个地址的这个demo包：
http://dev.cdn.buddhism.ouarea.cn/others/xpatch/demo.apk
执行：
java -jar ./xpatch.jar ./demo.apk -o output.apk

出现以上异常

**Comment by WindySha** [comment]
由于需要在应用的Application中插入一个init方法，以实现xposed插件的应用启动时的加载。
恰好这个Apk里的Application所在的dex文件方法数已经达到65536，在此dex中增加了一个方法导致方法数越界。
在当前破解方案下，暂时无法修复，后面有更好的破解方法后，再解此问题。

**Comment by WindySha** [comment]
3.0版本修复此问题
