### ISSUE TITLE
Error in version 4.2 when running on Windows OS

### ISSUE THREAD

**Issue by AsyncRes** [WindySha/Xpatch#90]
When patch apk with Xpatch 4.2, it shows an error `IOException: Cannot run program "chmod": CreateProcess error=2, The system cannot find the file specified`. But apk generate successfully. However the patched apk doesn't open after installed. It just crash. also apk name changes to something like "com.wind.Xpatch*** ".

**Comment by WindySha** [comment]
versioin updated, use v4.3.  The IOException can  be ignored if new apk is created.
